// Generated by gencpp from file raptors_task/AddTwoInts.msg
// DO NOT EDIT!


#ifndef RAPTORS_TASK_MESSAGE_ADDTWOINTS_H
#define RAPTORS_TASK_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <raptors_task/AddTwoIntsRequest.h>
#include <raptors_task/AddTwoIntsResponse.h>


namespace raptors_task
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace raptors_task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::raptors_task::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::raptors_task::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::raptors_task::AddTwoInts > {
  static const char* value()
  {
    return "raptors_task/AddTwoInts";
  }

  static const char* value(const ::raptors_task::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::raptors_task::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::raptors_task::AddTwoInts >
template<>
struct MD5Sum< ::raptors_task::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::raptors_task::AddTwoInts >::value();
  }
  static const char* value(const ::raptors_task::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::raptors_task::AddTwoIntsRequest> should match
// service_traits::DataType< ::raptors_task::AddTwoInts >
template<>
struct DataType< ::raptors_task::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::raptors_task::AddTwoInts >::value();
  }
  static const char* value(const ::raptors_task::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::raptors_task::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::raptors_task::AddTwoInts >
template<>
struct MD5Sum< ::raptors_task::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::raptors_task::AddTwoInts >::value();
  }
  static const char* value(const ::raptors_task::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::raptors_task::AddTwoIntsResponse> should match
// service_traits::DataType< ::raptors_task::AddTwoInts >
template<>
struct DataType< ::raptors_task::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::raptors_task::AddTwoInts >::value();
  }
  static const char* value(const ::raptors_task::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAPTORS_TASK_MESSAGE_ADDTWOINTS_H
